### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [BR903/frances-hodgson-burnett_a-little-princess#1]
### preface.xhtml:

- [x] The `<body>` semantics needs to be `epub:type="frontmatter z3998:fiction"`.

- [x] The `<section>` semantics needs to be `epub:type="preface"`.

- [x] The signature should be in a `<footer>` element.

- [x] Remove `class="epub-type-z3998-signature"` from the signature. We avoid using classes that are only used once or twice.

### chapter-3.xhtml:

- [x] `se build --check-only .` is complaining about the language tag `xml:lang="x-franglais"` because it is too long. Another way you could tag this is `xml:lang="x-fr-en"`.

### chapter-8.xhtml:

- [x] Mark `<i>h</i>` as a grapheme ([SEMOS 8.2.8.2](https://standardebooks.org/manual/1.7.0/single-page#8.2.8.2)).

### chapter-16.xhtml:

- [x] "The Little Girl in the Attic." should be in a `<footer>` element.

- [x] The semantics for "The Little Girl in the Attic." should be `epub:type="z3998:sender z3998:signature"` ([SEMOS 7.7.3.4](https://standardebooks.org/manual/1.7.0/single-page#7.7.3.4)). Remove `class="epub-type-z3998-signature"`.

### local.css:

- [x] Remove:
```
.epub-type-z3998-signature{
	font-variant: small-caps;
	margin-right: 1em;
	text-align: right;
}
```

- [x] Add CSS for `<footer>`s,   `epub:type="z3998:sender"`, and `epub:type="z3998:signature"` found in the example after  [SEMOS 7.7.3.5.1](https://standardebooks.org/manual/1.7.0/7-high-level-structural-patterns#7.7.3.5.1).

### toc.xhtml

- [x] Re-run `se build-toc .` after you've made the above changes.

### colophon.xhtml

- [x] The title of the artwork should be "I am not--I am not dreaming!"

### content.opf:

- [x] Add the role metadata `<meta property="se:role" refines="#author" scheme="marc:relators">wpr</meta>` to the author.

**Comment by BR903** [comment]
Thanks, this is great stuff.

A couple of quick follow-up questions:

> The semantics for "The Little Girl in the Attic." should be
> `epub:type="z3998:sender z3998:signature"`

Do we still mark a signature with "sender" when the note isn't actually _sent_, but is just left out for the addressee to see?

> The title of the artwork should be "I am not--I am not dreaming!"

I assume we don't preserve the emphasis in the original title then?
(Also, `se lint` complains that this lacks incorrect titlecasing; I will check in a `se-lint-ignore.xml` file to silence this.)

**Comment by EmmaSweeney** [comment]
> Do we still mark a signature with "sender" when the note isn't actually sent, but is just left out for the addressee to see?

Yes.

> I assume we don't preserve the emphasis in the original title then?
> (Also, se lint complains that this lacks incorrect titlecasing; I will check in a se-lint-ignore.xml file to silence this.)

The title should be italicized because it is a painting title. The title needs to be correctly titlecased.

**Comment by BR903** [comment]
> The title should be italicized because it is a painting title.

Sure! But to clarify, the original title contains emphasized words -- as per [the book's LoI page](https://archive.org/details/littleprincessbe00burn/page/n16/mode/1up). My question is: do we preserve the emphasis? (My assumption was that we don't, because we don't want to use HTML tags within a title.)

**Comment by EmmaSweeney** [comment]
You can use `<em>`s inside of titles.

**Comment by BR903** [comment]
All right. These should all be fixed now. Thanks again for all your help!

**Comment by EmmaSweeney** [comment]
- [ ] Re-run `se typogrify .`

- [ ] Re-run `se clean .`

- [ ] The styling for the footers should be:
```
footer{
	margin-top: 1em;
	text-align: right;
}
```

**Comment by BR903** [comment]
Done.
